// Daftar surah Juz 30 (An-Naba s/d An-Naas)
export const JUZ30_SURAHS = [
  { nomor: 78, nama: 'An-Naba', arti: "Berita Besar", ayat: 40 },
  { nomor: 79, nama: "An-Nazi'at", arti: "Malaikat yang Mencabut", ayat: 46 },
  { nomor: 80, nama: "'Abasa", arti: "Bermuka Masam", ayat: 42 },
  { nomor: 81, nama: "At-Takwir", arti: "Menggulung", ayat: 29 },
  { nomor: 82, nama: "Al-Infithar", arti: "Terbelah", ayat: 19 },
  { nomor: 83, nama: "Al-Muthaffifin", arti: "Orang yang Curang", ayat: 36 },
  { nomor: 84, nama: "Al-Insyiqaq", arti: "Terbelah", ayat: 25 },
  { nomor: 85, nama: "Al-Buruj", arti: "Gugusan Bintang", ayat: 22 },
  { nomor: 86, nama: "Ath-Thariq", arti: "Yang Datang di Malam Hari", ayat: 17 },
  { nomor: 87, nama: "Al-A'la", arti: "Yang Paling Tinggi", ayat: 19 },
  { nomor: 88, nama: "Al-Ghasyiyah", arti: "Hari Pembalasan", ayat: 26 },
  { nomor: 89, nama: "Al-Fajr", arti: "Fajar", ayat: 30 },
  { nomor: 90, nama: "Al-Balad", arti: "Negeri", ayat: 20 },
  { nomor: 91, nama: "Asy-Syams", arti: "Matahari", ayat: 15 },
  { nomor: 92, nama: "Al-Lail", arti: "Malam", ayat: 21 },
  { nomor: 93, nama: "Adh-Dhuha", arti: "Waktu Dhuha", ayat: 11 },
  { nomor: 94, nama: "Al-Insyirah", arti: "Kelapangan", ayat: 8 },
  { nomor: 95, nama: "At-Tin", arti: "Buah Tin", ayat: 8 },
  { nomor: 96, nama: "Al-'Alaq", arti: "Segumpal Darah", ayat: 19 },
  { nomor: 97, nama: "Al-Qadr", arti: "Kemuliaan", ayat: 5 },
  { nomor: 98, nama: "Al-Bayyinah", arti: "Bukti Nyata", ayat: 8 },
  { nomor: 99, nama: "Az-Zalzalah", arti: "Kegoncangan", ayat: 8 },
  { nomor: 100, nama: "Al-'Adiyat", arti: "Kuda Perang", ayat: 11 },
  { nomor: 101, nama: "Al-Qari'ah", arti: "Hari Kiamat", ayat: 11 },
  { nomor: 102, nama: "At-Takatsur", arti: "Bermegah-megahan", ayat: 8 },
  { nomor: 103, nama: "Al-'Ashr", arti: "Masa", ayat: 3 },
  { nomor: 104, nama: "Al-Humazah", arti: "Pengumpat", ayat: 9 },
  { nomor: 105, nama: "Al-Fil", arti: "Gajah", ayat: 5 },
  { nomor: 106, nama: "Quraisy", arti: "Suku Quraisy", ayat: 4 },
  { nomor: 107, nama: "Al-Ma'un", arti: "Barang yang Berguna", ayat: 7 },
  { nomor: 108, nama: "Al-Kautsar", arti: "Nikmat yang Banyak", ayat: 3 },
  { nomor: 109, nama: "Al-Kafirun", arti: "Orang-orang Kafir", ayat: 6 },
  { nomor: 110, nama: "An-Nashr", arti: "Pertolongan", ayat: 3 },
  { nomor: 111, nama: "Al-Lahab", arti: "Gejolak Api", ayat: 5 },
  { nomor: 112, nama: "Al-Ikhlas", arti: "Ikhlas", ayat: 4 },
  { nomor: 113, nama: "Al-Falaq", arti: "Waktu Subuh", ayat: 5 },
  { nomor: 114, nama: "An-Naas", arti: "Manusia", ayat: 6 },
];